name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: dart pub get

      - name: Run Tests
        run: dart test

      - name: Activate jaspr CLI
        run: |
          dart pub global activate jaspr_cli 0.22.2
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Set BASE_HREF
        run: |
          if [[ "${{ github.event.repository.name }}" == *.github.io ]]; then
            echo "BASE_HREF=/" >> $GITHUB_ENV
          else
            echo "BASE_HREF=/${{ github.event.repository.name }}/" >> $GITHUB_ENV
          fi
        
      - name: Build
        run: |
          jaspr build --optimize=2 --dart-define=BASE_HREF=$BASE_HREF
          touch build/jaspr/.nojekyll
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/jaspr
